FROM public.ecr.aws/lambda/python:3.11

RUN pip install --upgrade pip==22.0.4
RUN pip cache purge

# Copy function code
COPY ./src ${LAMBDA_TASK_ROOT}

# Set up environment variables
ARG EDS_API_URL
ENV EDS_API_URL=${EDS_API_URL}
ARG EDS_AUTH_URL
ENV EDS_AUTH_URL=${EDS_AUTH_URL}
ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ARG INPUT_JSON_PATH
ENV INPUT_JSON_PATH=${INPUT_JSON_PATH}
ARG GATEWAY_STAGE
ENV GATEWAY_STAGE=${GATEWAY_STAGE}

# Install the function's dependencies using file requirements.txt
# from your project folder.
COPY requirements.txt ${LAMBDA_TASK_ROOT}
# Install the specified packages
RUN pip install -r requirements.txt
# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "api.api.handler" ]